apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
images:
  - name: app
    newName: registry.digitalocean.com/dokr-saas/matmul
    newTag: v1.0.0

