apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocm-matmul-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ranjeethap/rocm-doks-demo.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true]

