apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocm-matmul
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ranjeethap/rocm-doks-demo.git  # 🔁 change this
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

