name: build-scan-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  REGISTRY: ${{ secrets.DOCR_REGISTRY }}
  IMAGE_REPO: ${{ secrets.DOCR_REPO }}
  DO_TOKEN: ${{ secrets.DO_TOKEN }}
  KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DOCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DOCR_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_REPO }}:git-${{ github.sha }}
      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_REPO }}:git-${{ github.sha }}
          format: sarif
          exit-code: '1'
          ignore-unfixed: true
      - name: Set KUBECONFIG
        run: |
          echo "${KUBECONFIG_DATA}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV
      - name: Deploy manifests
        run: |
          kubectl -n dev apply -f k8s/service.yaml
          yq e ".spec.template.spec.containers[0].image = "${IMAGE_REPO}:git-${GITHUB_SHA}"" k8s/deployment.yaml | kubectl apply -f -
          kubectl -n dev apply -f k8s/hpa.yaml
